### ISSUE TITLE
[PE-D] [BUG] Adding a new customer causes the sorting of the list to automatically change from ascending (default) to descending

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T17-1/tp#162]
This is what is looks like before adding a new customer (after doing a resetC to ensure its at its default settings). 
![Screenshot 2021-10-29 at 4.41.33 PM.png](https://raw.githubusercontent.com/ramaven/ped/main/files/f8818045-a58c-4036-9889-f55868335014.png)

After adding a new customer (addC n/zebra Doe p/00000000 e/zebra@u.nus.edu a/zebra lp/1000), this is the result shown:

![Screenshot 2021-10-29 at 4.42.59 PM.png](https://raw.githubusercontent.com/ramaven/ped/main/files/9227edbc-9b5a-45e8-986e-1e756ed79b39.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ramaven/ped#2

**Comment by clementkfj** [comment]
Think we have to test this out

**Comment by Javiier-pzk** [comment]
LMAO this man is on drugs I tested with the exact same command and mine wasn't like that

**Comment by clementkfj** [comment]
Thank you to this man for showing us a bug
