### ISSUE TITLE
[PE-D] delete commands index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T17-1/tp#170]
findC Lee
![image.png](https://raw.githubusercontent.com/thanwinnikki/ped/main/files/0e559c3d-4724-4fad-a310-69643ab3091b.png)

listS 

![image.png](https://raw.githubusercontent.com/thanwinnikki/ped/main/files/2662a1ba-641c-4afb-8730-7a01b4d91ba7.png)

deleteC 3

![image.png](https://raw.githubusercontent.com/thanwinnikki/ped/main/files/a03526b3-9b62-4695-85b7-11504a355fcc.png)

Same issue regarding edit commands indexes. Not sure if its an intended feature but index always refers to last displayed list's index for that specific list. In the UG it is said that Index refers to the index on the displayed list, but since I can call deleteC from the supplier list, then the index can be valid in the supplier list but not valid for the deleteC command. It is not specified what the Index is referring and on which list. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: thanwinnikki/ped#7

**Comment by Javiier-pzk** [comment]
tf? Man did deleteC and there are only 2 indexes in the customer list ofc deleteC3 returns false

**Comment by clementkfj** [comment]
> tf? Man did deleteC and there are only 2 indexes in the customer list ofc deleteC3 returns invalid

Man is high

**Comment by clementkfj** [comment]
Closing because we are not going to entertain such ridiculousness
