### ISSUE TITLE
[PE-D] addC command and whether all its fields are necessary.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T17-1/tp#171]
![image.png](https://raw.githubusercontent.com/thanwinnikki/ped/main/files/b2c5d078-8f13-4b7b-9524-eecd852e4a1b.png)

When going to a restaurant, I do not expect to tell them my email and address, most of the time the only necessary fields are email and address. Perhaps can look into making some more fields optional as well.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: thanwinnikki/ped#8

**Comment by clementkfj** [comment]
@chetwinlow thoughts?
